version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
       -  /Users/wesleywhitney/code/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${SHOESWAP_DB_PASSWORD}"
      MYSQL_DATABASE: "${SHOESWAP_DB_NAME}"
      MYSQL_PASSWORD: "${SHOESWAP_DB_PASSWORD}"